/* Site config */
#define PJ_CONFIG_ANDROID 1
#define PJ_CONFIG_MINIMAL_SIZE

/* Disable some codecs */

#define PJMEDIA_HAS_SPEEX_CODEC 0
#define PJMEDIA_HAS_G7221_CODEC 0
#define PJMEDIA_HAS_G722_CODEC 0
#define PJMEDIA_HAS_GSM_CODEC 0
#define PJMEDIA_HAS_SILK_CODEC 0
#define PJMEDIA_HAS_OPENCORE_AMRNB_CODEC 0
#define PJMEDIA_HAS_OPENCORE_AMRWB_CODEC 0
#define PJMEDIA_HAS_INTEL_IPP 0
#define PJMEDIA_HAS_L16_CODEC 0
#define PJMEDIA_HAS_PASSTHROUGH_CODECS 0
#define PJMEDIA_HAS_G711_CODEC 1
#define PJMEIDA_HAS_ILBC_CODEC 1

#include <pj/config_site_sample.h>

